[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:redis]
command=redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru --save "" --appendonly no
autostart=true
autorestart=true
priority=1
stderr_logfile=/var/log/redis.err.log
stdout_logfile=/var/log/redis.out.log

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
priority=5
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=10
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
